observation = [
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.0,
    "_label_": "Random Forest",
    "_ids_": 0,
    "_y_": 0
  }
];