profile = [
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 0,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.29,
    "_vname_": "odor",
    "_label_": "Random Forest",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 1,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.45,
    "_vname_": "odor",
    "_label_": "Random Forest",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 2,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.53,
    "_vname_": "odor",
    "_label_": "Random Forest",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.27,
    "_vname_": "odor",
    "_label_": "Random Forest",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 4,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.38,
    "_vname_": "odor",
    "_label_": "Random Forest",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.0,
    "_vname_": "odor",
    "_label_": "Random Forest",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 6,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.52,
    "_vname_": "odor",
    "_label_": "Random Forest",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 7,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.39,
    "_vname_": "odor",
    "_label_": "Random Forest",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 8,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.37,
    "_vname_": "odor",
    "_label_": "Random Forest",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.06,
    "_vname_": "gill-size",
    "_label_": "Random Forest",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.0,
    "_vname_": "gill-size",
    "_label_": "Random Forest",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.0,
    "_vname_": "gill-spacing",
    "_label_": "Random Forest",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.13,
    "_vname_": "gill-spacing",
    "_label_": "Random Forest",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 0,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.05,
    "_vname_": "stalk-surface-above-ring",
    "_label_": "Random Forest",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 1,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.19,
    "_vname_": "stalk-surface-above-ring",
    "_label_": "Random Forest",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.0,
    "_vname_": "stalk-surface-above-ring",
    "_label_": "Random Forest",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 3,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.04,
    "_vname_": "stalk-surface-above-ring",
    "_label_": "Random Forest",
    "_ids_": 0
  }
];