profile = [
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 0,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0,
    "_vname_": "odor",
    "_label_": "Random Forest",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 1,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.1,
    "_vname_": "odor",
    "_label_": "Random Forest",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 2,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.32,
    "_vname_": "odor",
    "_label_": "Random Forest",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0,
    "_vname_": "odor",
    "_label_": "Random Forest",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 4,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.04,
    "_vname_": "odor",
    "_label_": "Random Forest",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.07,
    "_vname_": "odor",
    "_label_": "Random Forest",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 6,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.11,
    "_vname_": "odor",
    "_label_": "Random Forest",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 7,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.04,
    "_vname_": "odor",
    "_label_": "Random Forest",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 8,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.03,
    "_vname_": "odor",
    "_label_": "Random Forest",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0,
    "_vname_": "gill-size",
    "_label_": "Random Forest",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.49,
    "_vname_": "gill-size",
    "_label_": "Random Forest",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0,
    "_vname_": "gill-spacing",
    "_label_": "Random Forest",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.03,
    "_vname_": "gill-spacing",
    "_label_": "Random Forest",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 0,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.09,
    "_vname_": "stalk-surface-above-ring",
    "_label_": "Random Forest",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 1,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.18,
    "_vname_": "stalk-surface-above-ring",
    "_label_": "Random Forest",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0,
    "_vname_": "stalk-surface-above-ring",
    "_label_": "Random Forest",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 3,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.06,
    "_vname_": "stalk-surface-above-ring",
    "_label_": "Random Forest",
    "_ids_": 0
  }
];