profile = [
  {
    "cap-shape": 0,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.001061609620344873,
    "_vname_": "cap-shape",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 1,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0010402433561444483,
    "_vname_": "cap-shape",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0007073747488164561,
    "_vname_": "cap-shape",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 3,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.000740981160552346,
    "_vname_": "cap-shape",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 4,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.00044514166726173515,
    "_vname_": "cap-shape",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0006404861623783175,
    "_vname_": "cap-shape",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 0,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0002878860699776713,
    "_vname_": "cap-surface",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 1,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.001258426961070116,
    "_vname_": "cap-surface",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 2,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0008426321809409845,
    "_vname_": "cap-surface",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0006404861623783175,
    "_vname_": "cap-surface",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 0,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.001975362826638055,
    "_vname_": "cap-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 1,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0003363522297537803,
    "_vname_": "cap-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 2,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0008432951111467304,
    "_vname_": "cap-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 3,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0008417005940531566,
    "_vname_": "cap-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 4,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0005402437181388162,
    "_vname_": "cap-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 5,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0018872612325264845,
    "_vname_": "cap-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 6,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0005756767307459333,
    "_vname_": "cap-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 7,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0005725726784567549,
    "_vname_": "cap-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 8,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0013199967135222159,
    "_vname_": "cap-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0006404861623783175,
    "_vname_": "cap-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 0,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.000530133169839572,
    "_vname_": "bruises%3F",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0006404861623783175,
    "_vname_": "bruises%3F",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 0,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0006636147023327795,
    "_vname_": "odor",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 1,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.13532163900743746,
    "_vname_": "odor",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 2,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.13175218992194115,
    "_vname_": "odor",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0006404861623783175,
    "_vname_": "odor",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 4,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.014316056738232663,
    "_vname_": "odor",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.00018378727465902752,
    "_vname_": "odor",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 6,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.08794107928419281,
    "_vname_": "odor",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 7,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0250095717791213,
    "_vname_": "odor",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 8,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.02421127940794717,
    "_vname_": "odor",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 0,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0004998819388983474,
    "_vname_": "gill-attachment",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0006404861623783175,
    "_vname_": "gill-attachment",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0006404861623783175,
    "_vname_": "gill-spacing",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 3.314268584699616e-05,
    "_vname_": "gill-spacing",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0006404861623783175,
    "_vname_": "gill-size",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.044632109786057333,
    "_vname_": "gill-size",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 0,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.008297152895298943,
    "_vname_": "gill-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 1,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0007359456172197113,
    "_vname_": "gill-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0012556367059521087,
    "_vname_": "gill-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 3,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0013898486763184962,
    "_vname_": "gill-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0008476490783698359,
    "_vname_": "gill-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0006404861623783175,
    "_vname_": "gill-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 6,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.001142535727515331,
    "_vname_": "gill-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 7,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0008453749363234146,
    "_vname_": "gill-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 8,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0022630597957124096,
    "_vname_": "gill-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 9,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.00098499121830268,
    "_vname_": "gill-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 10,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0008506776215722216,
    "_vname_": "gill-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 11,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0016304592474001458,
    "_vname_": "gill-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0006404861623783175,
    "_vname_": "stalk-shape",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 1,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.00018427821136167096,
    "_vname_": "stalk-shape",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 0,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0010228506778912037,
    "_vname_": "stalk-root",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 1,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.01842951509596766,
    "_vname_": "stalk-root",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0006404861623783175,
    "_vname_": "stalk-root",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0019131158060824995,
    "_vname_": "stalk-root",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 4,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0006810593167364138,
    "_vname_": "stalk-root",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 0,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.001001922777159793,
    "_vname_": "stalk-surface-above-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 1,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.011159030422490756,
    "_vname_": "stalk-surface-above-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0006404861623783175,
    "_vname_": "stalk-surface-above-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 3,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.002249872193281715,
    "_vname_": "stalk-surface-above-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 0,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0003319748105784484,
    "_vname_": "stalk-surface-below-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 1,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0014968470840909934,
    "_vname_": "stalk-surface-below-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0006404861623783175,
    "_vname_": "stalk-surface-below-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 3,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0036151673199925497,
    "_vname_": "stalk-surface-below-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 0,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0008236464766895056,
    "_vname_": "stalk-color-above-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 1,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0009299551205725098,
    "_vname_": "stalk-color-above-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 2,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0004163408394391124,
    "_vname_": "stalk-color-above-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 3,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.00046702742658144645,
    "_vname_": "stalk-color-above-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 4,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.000576401044550402,
    "_vname_": "stalk-color-above-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 5,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0005009701206944678,
    "_vname_": "stalk-color-above-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 6,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.000903972696485928,
    "_vname_": "stalk-color-above-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0006404861623783175,
    "_vname_": "stalk-color-above-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 8,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0012051898498561433,
    "_vname_": "stalk-color-above-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 0,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0005458706952041338,
    "_vname_": "stalk-color-below-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 1,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0006538918968301362,
    "_vname_": "stalk-color-below-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 2,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0003248515879446329,
    "_vname_": "stalk-color-below-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 3,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.00034384401372188636,
    "_vname_": "stalk-color-below-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 4,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0001829264506914403,
    "_vname_": "stalk-color-below-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 5,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0003522089887535699,
    "_vname_": "stalk-color-below-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 6,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0006772056127952078,
    "_vname_": "stalk-color-below-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0006404861623783175,
    "_vname_": "stalk-color-below-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 8,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0011306241179771098,
    "_vname_": "stalk-color-below-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0006404861623783175,
    "_vname_": "veil-type",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 0,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0007219666243382055,
    "_vname_": "veil-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 1,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0007280584982298924,
    "_vname_": "veil-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0006404861623783175,
    "_vname_": "veil-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 3,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.001499710432557615,
    "_vname_": "veil-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 0,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0009628406402348395,
    "_vname_": "ring-number",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0006404861623783175,
    "_vname_": "ring-number",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 2,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0005592848155963386,
    "_vname_": "ring-number",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0013206350488042071,
    "_vname_": "ring-type",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 1,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.00015166896307670667,
    "_vname_": "ring-type",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 2,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0013697572411613776,
    "_vname_": "ring-type",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 3,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.000962409432824059,
    "_vname_": "ring-type",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0006404861623783175,
    "_vname_": "ring-type",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 0,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.002827252854751285,
    "_vname_": "spore-print-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 1,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.008111720197699923,
    "_vname_": "spore-print-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0007830629245105137,
    "_vname_": "spore-print-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0006404861623783175,
    "_vname_": "spore-print-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 4,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0027539236646225425,
    "_vname_": "spore-print-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 5,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0886997018333609,
    "_vname_": "spore-print-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 6,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0007109843151985682,
    "_vname_": "spore-print-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 7,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0037487438059030103,
    "_vname_": "spore-print-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 8,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0027309886287015545,
    "_vname_": "spore-print-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 3,
    "_yhat_": 0.00137132865498705,
    "_vname_": "population",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 1,
    "habitat": 3,
    "_yhat_": 0.005070975456398326,
    "_vname_": "population",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0006404861623783175,
    "_vname_": "population",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 3,
    "habitat": 3,
    "_yhat_": 0.0019375403338617568,
    "_vname_": "population",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 4,
    "habitat": 3,
    "_yhat_": 0.0020017727677638887,
    "_vname_": "population",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 5,
    "habitat": 3,
    "_yhat_": 0.0004265446850359543,
    "_vname_": "population",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 0,
    "_yhat_": 0.00021754481329892836,
    "_vname_": "habitat",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 1,
    "_yhat_": 0.0006057383645880438,
    "_vname_": "habitat",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 2,
    "_yhat_": 0.0003259788357628292,
    "_vname_": "habitat",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 3,
    "_yhat_": 0.0006404861623783175,
    "_vname_": "habitat",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 4,
    "_yhat_": 0.0002160835574832066,
    "_vname_": "habitat",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 5,
    "_yhat_": 0.0004081843874494984,
    "_vname_": "habitat",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 3,
    "cap-color": 9,
    "bruises%3F": 1,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 6,
    "_yhat_": 9.583782195643129e-05,
    "_vname_": "habitat",
    "_label_": "Logistic Regression",
    "_ids_": 0
  }
];