profile = [
  {
    "cap-shape": 0,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.00010740028031302605,
    "_vname_": "cap-shape",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 1,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.00010523668782629041,
    "_vname_": "cap-shape",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 7.154045843452603e-05,
    "_vname_": "cap-shape",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 3,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 7.494151367143164e-05,
    "_vname_": "cap-shape",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 4,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 4.5008857119923e-05,
    "_vname_": "cap-shape",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 6.477177345805336e-05,
    "_vname_": "cap-shape",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 2.442945229251728e-05,
    "_vname_": "cap-surface",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 1,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.0001068826243627026,
    "_vname_": "cap-surface",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 7.154045843452603e-05,
    "_vname_": "cap-surface",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 3,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 5.436795919178771e-05,
    "_vname_": "cap-surface",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 0,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.00016807072444041703,
    "_vname_": "cap-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 1,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 2.857508016019906e-05,
    "_vname_": "cap-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 2,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 7.167608929834012e-05,
    "_vname_": "cap-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 7.154045843452603e-05,
    "_vname_": "cap-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 4.590541659708439e-05,
    "_vname_": "cap-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 5,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.0001605617672778332,
    "_vname_": "cap-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 6,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 4.891780610333702e-05,
    "_vname_": "cap-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 7,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 4.865390273691282e-05,
    "_vname_": "cap-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 8,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.00011224246681920046,
    "_vname_": "cap-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 9,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 5.442818064494991e-05,
    "_vname_": "cap-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 7.154045843452603e-05,
    "_vname_": "bruises%3F",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 1,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 8.64406400374883e-05,
    "_vname_": "bruises%3F",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 0,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.0002583923149896798,
    "_vname_": "odor",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 1,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.057414419353786765,
    "_vname_": "odor",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 2,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.05576743225047862,
    "_vname_": "odor",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.0002493832080755766,
    "_vname_": "odor",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 4,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.0056211494791071565,
    "_vname_": "odor",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 7.154045843452603e-05,
    "_vname_": "odor",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 6,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.03617067057457783,
    "_vname_": "odor",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 7,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.00988505400965857,
    "_vname_": "odor",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 8,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.009564792278925018,
    "_vname_": "odor",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 0,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 5.582839451080638e-05,
    "_vname_": "gill-attachment",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 7.154045843452603e-05,
    "_vname_": "gill-attachment",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.0013815553172552258,
    "_vname_": "gill-spacing",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 7.154045843452603e-05,
    "_vname_": "gill-spacing",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 7.154045843452603e-05,
    "_vname_": "gill-size",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 1,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.00518814989901757,
    "_vname_": "gill-size",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 0,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.0007050819903160487,
    "_vname_": "gill-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 1,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 6.210647702476517e-05,
    "_vname_": "gill-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 2,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.00010601370875173519,
    "_vname_": "gill-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 3,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.00011735969699394746,
    "_vname_": "gill-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 7.154045843452603e-05,
    "_vname_": "gill-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 5,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 5.4045922919196465e-05,
    "_vname_": "gill-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 6,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 9.645456536524767e-05,
    "_vname_": "gill-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 7,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 7.134837517262116e-05,
    "_vname_": "gill-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 8,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.00019124730406069575,
    "_vname_": "gill-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 9,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 8.314241704451173e-05,
    "_vname_": "gill-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 10,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 7.179626272117981e-05,
    "_vname_": "gill-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 11,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.00013770738328543346,
    "_vname_": "gill-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.00024871886790297875,
    "_vname_": "stalk-shape",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 7.154045843452603e-05,
    "_vname_": "stalk-shape",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 0,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 3.8216416712503156e-05,
    "_vname_": "stalk-root",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 1,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.0007003224411000584,
    "_vname_": "stalk-root",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 2.3921449357305994e-05,
    "_vname_": "stalk-root",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 7.154045843452603e-05,
    "_vname_": "stalk-root",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 4,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 2.5437805952735364e-05,
    "_vname_": "stalk-root",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 0,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.00011194785222639861,
    "_vname_": "stalk-surface-above-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 1,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.0012581952116452362,
    "_vname_": "stalk-surface-above-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 7.154045843452603e-05,
    "_vname_": "stalk-surface-above-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 3,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.0002516642551840962,
    "_vname_": "stalk-surface-above-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 0,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 3.7070463850716676e-05,
    "_vname_": "stalk-surface-below-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 1,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.00016732086920585157,
    "_vname_": "stalk-surface-below-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 7.154045843452603e-05,
    "_vname_": "stalk-surface-below-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 3,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.0004048743033524555,
    "_vname_": "stalk-surface-below-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 0,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 9.201391809684872e-05,
    "_vname_": "stalk-color-above-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 1,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.00010390004038000958,
    "_vname_": "stalk-color-above-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 2,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 4.649480839177457e-05,
    "_vname_": "stalk-color-above-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 3,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 5.2157575766972316e-05,
    "_vname_": "stalk-color-above-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 4,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 6.43786682357321e-05,
    "_vname_": "stalk-color-above-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 5,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 5.59499802034473e-05,
    "_vname_": "stalk-color-above-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 6,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.00010099479849005161,
    "_vname_": "stalk-color-above-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 7.154045843452603e-05,
    "_vname_": "stalk-color-above-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 8,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.0001346838373023248,
    "_vname_": "stalk-color-above-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 0,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 6.09670560422974e-05,
    "_vname_": "stalk-color-below-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 1,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 7.303871066515624e-05,
    "_vname_": "stalk-color-below-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 2,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 3.627480892325197e-05,
    "_vname_": "stalk-color-below-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 3,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 3.839626115316794e-05,
    "_vname_": "stalk-color-below-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 4,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 2.0424050633309536e-05,
    "_vname_": "stalk-color-below-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 5,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 3.933065081791114e-05,
    "_vname_": "stalk-color-below-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 6,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 7.564438416874363e-05,
    "_vname_": "stalk-color-below-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 7.154045843452603e-05,
    "_vname_": "stalk-color-below-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 8,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.00012634249911696184,
    "_vname_": "stalk-color-below-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 7.154045843452603e-05,
    "_vname_": "veil-type",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 0,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 8.064743215404035e-05,
    "_vname_": "veil-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 1,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 8.132836661267108e-05,
    "_vname_": "veil-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 7.154045843452603e-05,
    "_vname_": "veil-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 3,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.00016764136761178607,
    "_vname_": "veil-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 0,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.00010757734891998218,
    "_vname_": "ring-number",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 7.154045843452603e-05,
    "_vname_": "ring-number",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 2,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 6.246599337737196e-05,
    "_vname_": "ring-number",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 7.154045843452603e-05,
    "_vname_": "ring-type",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 1,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 8.207012111044153e-06,
    "_vname_": "ring-type",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 2,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 7.420492146680647e-05,
    "_vname_": "ring-type",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 3,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 5.211724540274714e-05,
    "_vname_": "ring-type",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 3.467360426373474e-05,
    "_vname_": "ring-type",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 0,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.00031641102149023754,
    "_vname_": "spore-print-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 1,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.0009121130854491744,
    "_vname_": "spore-print-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 2,
    "population": 0,
    "habitat": 1,
    "_yhat_": 8.747695802882129e-05,
    "_vname_": "spore-print-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 7.154045843452603e-05,
    "_vname_": "spore-print-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 4,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.00030818428398155065,
    "_vname_": "spore-print-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 5,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.010748849963971843,
    "_vname_": "spore-print-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 6,
    "population": 0,
    "habitat": 1,
    "_yhat_": 7.941987568143927e-05,
    "_vname_": "spore-print-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 7,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.00041988395288096545,
    "_vname_": "spore-print-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 8,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.0003056114430005204,
    "_vname_": "spore-print-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 7.154045843452603e-05,
    "_vname_": "population",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 1,
    "habitat": 1,
    "_yhat_": 0.0002654785067762675,
    "_vname_": "population",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 2,
    "habitat": 1,
    "_yhat_": 3.3390180589827926e-05,
    "_vname_": "population",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 3,
    "habitat": 1,
    "_yhat_": 0.00010113334614636313,
    "_vname_": "population",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 4,
    "habitat": 1,
    "_yhat_": 0.00010449244551042124,
    "_vname_": "population",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 5,
    "habitat": 1,
    "_yhat_": 2.2232353240020425e-05,
    "_vname_": "population",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 0,
    "_yhat_": 2.5684234578782356e-05,
    "_vname_": "habitat",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 7.154045843452603e-05,
    "_vname_": "habitat",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 2,
    "_yhat_": 3.849008251972698e-05,
    "_vname_": "habitat",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 3,
    "_yhat_": 7.564665105549466e-05,
    "_vname_": "habitat",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 4,
    "_yhat_": 2.5511679827760963e-05,
    "_vname_": "habitat",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 5,
    "_yhat_": 4.8200031791934326e-05,
    "_vname_": "habitat",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 6,
    "_yhat_": 1.1313792409173614e-05,
    "_vname_": "habitat",
    "_label_": "Logistic Regression",
    "_ids_": 0
  }
];