profile = [
  {
    "cap-shape": 0,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.020767880698621614,
    "_vname_": "cap-shape",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 1,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.02035798313213697,
    "_vname_": "cap-shape",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.013929806712260195,
    "_vname_": "cap-shape",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 3,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.014582426004647039,
    "_vname_": "cap-shape",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 4,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.008809055134803689,
    "_vname_": "cap-shape",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 5,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.012628419823563022,
    "_vname_": "cap-shape",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.013929806712260195,
    "_vname_": "cap-surface",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 1,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.058212893844478274,
    "_vname_": "cap-surface",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.03972740900992254,
    "_vname_": "cap-surface",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 3,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.03048145429308475,
    "_vname_": "cap-surface",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 0,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.049183041103712126,
    "_vname_": "cap-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 1,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.008716679051769474,
    "_vname_": "cap-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 2,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.021581589937666436,
    "_vname_": "cap-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.021541628501637124,
    "_vname_": "cap-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.013929806712260195,
    "_vname_": "cap-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 5,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.04708880762470384,
    "_vname_": "cap-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 6,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.014830391349977648,
    "_vname_": "cap-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 7,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.014751560273544745,
    "_vname_": "cap-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 8,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.03338956939292452,
    "_vname_": "cap-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 9,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.016473538457633913,
    "_vname_": "cap-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.013929806712260195,
    "_vname_": "bruises%3F",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 1,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.016782611311893042,
    "_vname_": "bruises%3F",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 0,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.04855457716094124,
    "_vname_": "odor",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 1,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.9232359218027991,
    "_vname_": "odor",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 2,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.9210207052340609,
    "_vname_": "odor",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.04694073688260022,
    "_vname_": "odor",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 4,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.5274466689814626,
    "_vname_": "odor",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.013929806712260195,
    "_vname_": "odor",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 6,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.8810921709011054,
    "_vname_": "odor",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 7,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.6634444968098385,
    "_vname_": "odor",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 8,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.6559784593942372,
    "_vname_": "odor",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 0,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.010903663698631192,
    "_vname_": "gill-attachment",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.013929806712260195,
    "_vname_": "gill-attachment",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.013929806712260195,
    "_vname_": "gill-spacing",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.00073001905147829,
    "_vname_": "gill-spacing",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.000193760089272017,
    "_vname_": "gill-size",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.013929806712260195,
    "_vname_": "gill-size",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 0,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.08593176775682754,
    "_vname_": "gill-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 1,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.008207555927452372,
    "_vname_": "gill-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.013929806712260195,
    "_vname_": "gill-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 3,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.015397844198581565,
    "_vname_": "gill-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 4,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.009442600664556208,
    "_vname_": "gill-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 5,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.00714988877996003,
    "_vname_": "gill-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 6,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.01268958980878568,
    "_vname_": "gill-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 7,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.009417484629987356,
    "_vname_": "gill-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 8,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.024852935489466252,
    "_vname_": "gill-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 9,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.010957285837636613,
    "_vname_": "gill-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 10,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.0094760466415496,
    "_vname_": "gill-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 11,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.018019758748937482,
    "_vname_": "gill-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.013929806712260195,
    "_vname_": "stalk-shape",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.004046154837979585,
    "_vname_": "stalk-shape",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 0,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.007489556751720223,
    "_vname_": "stalk-root",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 1,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.12155463435902499,
    "_vname_": "stalk-root",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 2,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.004701168763706822,
    "_vname_": "stalk-root",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.013929806712260195,
    "_vname_": "stalk-root",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 4,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.004997689339078431,
    "_vname_": "stalk-root",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 0,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.021628317221118912,
    "_vname_": "stalk-surface-above-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 1,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.1991941228589571,
    "_vname_": "stalk-surface-above-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.013929806712260195,
    "_vname_": "stalk-surface-above-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 3,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.04734986534464544,
    "_vname_": "stalk-surface-above-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 0,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.0072665994810226665,
    "_vname_": "stalk-surface-below-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 1,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.03198592582331189,
    "_vname_": "stalk-surface-below-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.013929806712260195,
    "_vname_": "stalk-surface-below-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 3,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.07405205668428436,
    "_vname_": "stalk-surface-below-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 0,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.017845461526292627,
    "_vname_": "stalk-color-above-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 1,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.020104581559984014,
    "_vname_": "stalk-color-above-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 2,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.009097250596278837,
    "_vname_": "stalk-color-above-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 3,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.01019399935570846,
    "_vname_": "stalk-color-above-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 4,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.012552734110267152,
    "_vname_": "stalk-color-above-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 5,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.010927152040628033,
    "_vname_": "stalk-color-above-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 6,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.019553355872580336,
    "_vname_": "stalk-color-above-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.013929806712260195,
    "_vname_": "stalk-color-above-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 8,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.025907682463352084,
    "_vname_": "stalk-color-above-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 0,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.011895401166749187,
    "_vname_": "stalk-color-below-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 1,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.014217408227914147,
    "_vname_": "stalk-color-below-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 2,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.007111737756664981,
    "_vname_": "stalk-color-below-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 3,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.007524538347983278,
    "_vname_": "stalk-color-below-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 4,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.004016588340983928,
    "_vname_": "stalk-color-below-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 5,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.007706247284924918,
    "_vname_": "stalk-color-below-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 6,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.01471719078061347,
    "_vname_": "stalk-color-below-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.013929806712260195,
    "_vname_": "stalk-color-below-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 8,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.02434200863238644,
    "_vname_": "stalk-color-below-ring",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.013929806712260195,
    "_vname_": "veil-type",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 0,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.01567539099921084,
    "_vname_": "veil-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 1,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.015805662475485094,
    "_vname_": "veil-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.013929806712260195,
    "_vname_": "veil-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 3,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.03204524055346861,
    "_vname_": "veil-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 0,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.020801411647036302,
    "_vname_": "ring-number",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.013929806712260195,
    "_vname_": "ring-number",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 2,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.01218431636762011,
    "_vname_": "ring-number",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.02832228217231425,
    "_vname_": "ring-type",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 1,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.0033324387359140416,
    "_vname_": "ring-type",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 2,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.02934624170619788,
    "_vname_": "ring-type",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 3,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.020792280662433955,
    "_vname_": "ring-type",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.013929806712260195,
    "_vname_": "ring-type",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 0,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.04862358918393422,
    "_vname_": "spore-print-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 1,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.1284780449346867,
    "_vname_": "spore-print-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.013929806712260195,
    "_vname_": "spore-print-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 3,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.011420886470716665,
    "_vname_": "spore-print-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 4,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.04741894481596852,
    "_vname_": "spore-print-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 5,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.6369617835858493,
    "_vname_": "spore-print-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 6,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.012662945178143743,
    "_vname_": "spore-print-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 7,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.06352072325751947,
    "_vname_": "spore-print-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 8,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.04704158031811246,
    "_vname_": "spore-print-color",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 0,
    "habitat": 5,
    "_yhat_": 0.04348282306556602,
    "_vname_": "population",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 1,
    "habitat": 5,
    "_yhat_": 0.14436883202503373,
    "_vname_": "population",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 2,
    "habitat": 5,
    "_yhat_": 0.0207757916013699,
    "_vname_": "population",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 3,
    "habitat": 5,
    "_yhat_": 0.06038517514572895,
    "_vname_": "population",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 4,
    "habitat": 5,
    "_yhat_": 0.06226615341766841,
    "_vname_": "population",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.013929806712260195,
    "_vname_": "population",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 0,
    "_yhat_": 0.007471192116562212,
    "_vname_": "habitat",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 1,
    "_yhat_": 0.020537130710268758,
    "_vname_": "habitat",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 2,
    "_yhat_": 0.011154827458294566,
    "_vname_": "habitat",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 3,
    "_yhat_": 0.021690415406680007,
    "_vname_": "habitat",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 4,
    "_yhat_": 0.0074213695382568555,
    "_vname_": "habitat",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 5,
    "_yhat_": 0.013929806712260195,
    "_vname_": "habitat",
    "_label_": "Logistic Regression",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 0,
    "cap-color": 4,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 1,
    "gill-color": 2,
    "stalk-shape": 0,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 4,
    "spore-print-color": 2,
    "population": 5,
    "habitat": 6,
    "_yhat_": 0.0033047947286179466,
    "_vname_": "habitat",
    "_label_": "Logistic Regression",
    "_ids_": 0
  }
];