profile = [
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 0,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.15,
    "_vname_": "odor",
    "_label_": "Random Forest",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 1,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.27,
    "_vname_": "odor",
    "_label_": "Random Forest",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 2,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.44,
    "_vname_": "odor",
    "_label_": "Random Forest",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 3,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.14,
    "_vname_": "odor",
    "_label_": "Random Forest",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 4,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.21,
    "_vname_": "odor",
    "_label_": "Random Forest",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.0,
    "_vname_": "odor",
    "_label_": "Random Forest",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 6,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.23,
    "_vname_": "odor",
    "_label_": "Random Forest",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 7,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.22,
    "_vname_": "odor",
    "_label_": "Random Forest",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 8,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.2,
    "_vname_": "odor",
    "_label_": "Random Forest",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.0,
    "_vname_": "gill-size",
    "_label_": "Random Forest",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 1,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.25,
    "_vname_": "gill-size",
    "_label_": "Random Forest",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 0,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.09,
    "_vname_": "gill-spacing",
    "_label_": "Random Forest",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.0,
    "_vname_": "gill-spacing",
    "_label_": "Random Forest",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 0,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.0,
    "_vname_": "stalk-surface-above-ring",
    "_label_": "Random Forest",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 1,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.11,
    "_vname_": "stalk-surface-above-ring",
    "_label_": "Random Forest",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 2,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.0,
    "_vname_": "stalk-surface-above-ring",
    "_label_": "Random Forest",
    "_ids_": 0
  },
  {
    "cap-shape": 2,
    "cap-surface": 2,
    "cap-color": 3,
    "bruises%3F": 0,
    "odor": 5,
    "gill-attachment": 1,
    "gill-spacing": 1,
    "gill-size": 0,
    "gill-color": 4,
    "stalk-shape": 1,
    "stalk-root": 3,
    "stalk-surface-above-ring": 3,
    "stalk-surface-below-ring": 2,
    "stalk-color-above-ring": 7,
    "stalk-color-below-ring": 7,
    "veil-type": 0,
    "veil-color": 2,
    "ring-number": 1,
    "ring-type": 0,
    "spore-print-color": 3,
    "population": 0,
    "habitat": 1,
    "_yhat_": 0.03,
    "_vname_": "stalk-surface-above-ring",
    "_label_": "Random Forest",
    "_ids_": 0
  }
];